---

- hosts: all
  become: true
  tasks:

  - name: Actualizacion de repository index
    apt:
      update_cache: yes

  - name: Instalacion de Apache
    apt:
      name: apache2
      state: latest

  - name: Adicionando PHP_Support para Apache
    apt:
      name: libapache2-mod-php
      state: latest
