---

- hosts: all
  become: true
  pre_tasks:

  - name: Instala actualizaciones (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Instala actualizaciones (Ubuntu)
    tags: always
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: Instala Apache y PHP en Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Instala Apache y PHP en CentOS
    tags: apache,httpd,centos
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Inicia el servicio httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Cambia email_admin en congifFile httpd (CentOS)
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin jvincent.camacho@gmail.com
    when: ansible_distribution == "CentOS"
    register: estado_de_httpd

  - name: Reinicia servicio httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: estado_de_httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: archivos/mi_website.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstations
  become: true
  tasks:

    - name: Instalacion de Unzip
      tags: workstations,pcs
      package:
        name: unzip

    - name: Instalacion de Terraform
      tags: workstations,pcs
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root


- hosts: db_servers
  become: true
  tasks:

  - name: Instala mariaDB paquete (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Instala mariaDB paquete (CentOS)
    tags: db,mariadb,centos    
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: Instala Samba tanto en Ubuntu como CentOS
    tags: samba
    package:
      name: samba
      state: latest
