---

- hosts: all
  become: true
  tasks:

  - name: Actualizacion IndexRepository en Debian/Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Instalacion de Apache en Debian/Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Adicionando PHP_Support para Apache en Debian/Ubuntu
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Actualizacion IndexRepository en CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Instalacion de Apache en CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Adicionando PHP_Support para Apache en CentOS
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
