- name: Instala mariaDB paquete (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Instala mariaDB paquete (CentOS)
  tags: db,mariadb,centos
  dnf:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"
